### ISSUE TITLE
received error

### ISSUE THREAD

**Issue by andrey0001** [bi-zone/Log4j_Detector#1]
![909957A1-3963-4CBF-9873-FA2A6B03FFCE](https://user-images.githubusercontent.com/5690286/146054340-d9bb802e-10c9-47ea-b5fd-e66042013af2.jpeg)

**Comment by apext1431** [comment]
Check file name Log4j.yar.  You need rename log4j.yar on Log4j.yar or use this command 

`ps -eo pid,comm | grep -i java | grep -Eo '[0-9].*' | cut -d ' ' -f 1 | xargs -I '{}' yara log4j.yar '{}' > scan_results.txt`

**Comment by Seffirot** [comment]
Hi @andrey0001 ! 
Thank you, we fixed the readme thanks to your comment!
